### ISSUE TITLE
Windows: Cache overgrow due StableName and Weak references

### ISSUE THREAD

**Issue by NCrashed** [tobbebex/GPipe#14]
I was testing my game under Windows (7 x64, ghc 7.8.3), and noticed memory leak:

![image](https://cloud.githubusercontent.com/assets/2116167/8808735/7ab79356-2ff5-11e5-9047-a0830055261d.png)

After some time of debugging I found that cache of vertex buffers grows all time. Actually [createVertexBuffer](https://github.com/tobbebex/GPipe/blob/master/src/Resources.hs#L212) is source of problems. 

Due some unknown reasons for each frame stable frames are always different, that leads to creation of new buffer and that woul be OK if finalizers operate properly. They are not always called, about 20% of buffers are not collected...

Perhaps weak pointers and stable names are not best implementation for caching? 

At the moment I fix the issue with switching off caching on Windows with conditional compilation. @tobbebex do you have an idea to fix this without drammatic fall of performance? I have an idea to lift special id to primitive stream API, user pass new id when data is changed.

**Comment by tobbebex** [comment]
This is probably due to both or either of:
* addFinalizer is unpredictable in haskell (for GPipe 2 I am using finalizers on IORefs instead which are predictable, see discussion in System.Mem.Weak haddocks).
* the finalizer is running concurrently with other threads and that wont work with OpenGl, instead the finalizing code would need to be dispatched to the right thread to work.

Still, the real problem of constantly creating new VBOs would remain, and it is not trivial to fix given the model used in GPipe 1. 

All of the above is fixed in GPipe 2 that is approaching completion. Since I plan to have that released in a month or so, I wont unfortunately spend any more work on GPipe 1. I am happy to accept pull requests though.

**Comment by tobbebex** [comment]
BTW, have you tried running compiling without the threaded runtime? (-threaded)

**Comment by NCrashed** [comment]
> All of the above is fixed in GPipe 2 that is approaching completion. Since I plan to have that released in a month or so, I wont unfortunately spend any more work on GPipe 1. I am happy to accept pull requests though.

I will wait for GPipe 2, the workaround with disabling caching is good enough to endure until new generation of the library is realeased ... 

> BTW, have you tried running compiling without the threaded runtime? (-threaded)

Turning off either optimization either threaded doesn't affect the bug.

**Comment by tobbebex** [comment]
Fixed in GPipe 2 that is hosted at https://github.com/tobbebex/GPipe-Core
